### ISSUE TITLE
Crawl hangs since over a week

### ISSUE THREAD

**Issue by klaus-aunds** [StJudeWasHere/seonaut#12] opened 2023-11-13 23:09 UTC
**Describe the bug**
A crawl was started but it doesn't ever finish. The UI only shows "Crawling...". This status has lasted for over a week now.

Fully stopping docker and starting it again didn't help. I'm not sure where to find debug information for this issue, therefore excuse the vagueness. Please let me know which information I can add.

**To Reproduce**
No steps to reproduce, happens randomly. So far only twice, both projects during the same day. Since then it hasn't occurred again.

**Expected behavior**
Crawl either finishes successfully or breaks on no activity after a certain amount of time or after a configured max timeout. An option to cancel the crawl would be a nice feature to have (as in https://github.com/StJudeWasHere/seonaut/issues/4). The option to delete the project (and thus also cancel the crawl) could also be available at all times, even when a crawl is running.

**Comment by StJudeWasHere** [comment] 2023-11-16 11:13
The issue you describe could be caused by the crawler crashing at some point or by SEOnaut being restarted while crawling a site. Once SEOnaut restarts, the crawler doesn't automatically start, but the unfinished crawl is still marked as "crawling" in the database. If this happens again, you can check the Docker logs to see the error stack trace. That would help us pinpoint the issue.

On the other hand, make sure you are using the latest code available, as some bugs have been fixed in this regard. Also, I pushed a change today, so restarting SEOnaut will cleanup the database if needed.

Adding an option to cancel a crawl is in the backlog too, and it will be added at some point.

I'm closing the issue as I think this is already fixed in the latest code, but feel free to open it again if this keeps happening.

Thanks for reporting the issue.

**Closed by StJudeWasHere** 2023-11-16 11:13 UTC
Labels: bug
