### ISSUE TITLE
Password not working and username

### ISSUE THREAD

**Issue by Iamtheoldman** [StJudeWasHere/seonaut#9] opened 2023-08-17 17:34 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by StJudeWasHere** [comment] 2023-08-18 08:12
I can't reproduce this. If you're still experiencing issues feel free to open it again providing more details and I'll look into it.

Thanks.

**Comment by garyritchie** [comment] 2024-03-29 19:21
I think I was having a similar issue in Chrome. I had moved the container storage and re-created the containers. Site would refresh when entering user/pass but would not log in, even after creating a new user. Login worked fine with Firefox (no previous login). The fix for Chrome was to _Delete data_ found in _Site settings_.

**Comment by StJudeWasHere** [comment] 2024-03-31 10:11
This seems to happen when SEOnaut is restarted, the cookies stored in the browser stop being valid and causes this behaviour. Removing them fixes the issue. 

I'll look into it, thanks for reporting.

**Comment by StJudeWasHere** [comment] 2024-04-03 14:05
Should be fixed in b035660

**Closed by StJudeWasHere** 2024-04-03 14:05 UTC
Labels: bug

**Comment by garyritchie** [comment] 2024-04-13 16:47
Thanks, no more issues with logging in.

**Comment by moonsuyoung** [comment] 2024-04-27 08:11
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xueyou2000, @walkingbean, @JDodson70, @rovertvj, @calmcc, @hbhghong, @DrSlaughter, @the4ndy, @GenaroSanada, @emean1010, @ahmedmaher05, @xixizy, @h2zzhou, @alugarius, @capsl, @7x6r3n7o, @ronanhardiman, @weiqilin66, @work4life2, @ollcp, @philcryer, @ajay-a1, @avioli, @Disaeon, @elhios, @waglero, @chaihahaha, @Pernat1y, @dreday966, @lp380490944, @panterarocks49, @abdifatahd60, @typebrook, @gc87, @christianwol-ff, @wjl1008, @polluxx, @TechniSal, @mrgleam, @wxyedward, @d1f3n1k0s, @kunode, @li5414, @worldnetcn, @Balatzar, @snqtbumpng, @an0o0nym, @firelife, @n7n-dev, @ferigeek
